jasmine = User.create(username: 'jasmine', email: 'jasmine@test.com', password: 'jasmine')
aladdin = User.create(username: 'aladdin', email: 'aladdin@test.com', password: 'aladdin')
genie = User.create(username: 'genie', email: 'genie@test.com', password: 'genie')
jafar = User.create(username: 'jafar', email: 'jafar@test.com', password: 'jafar')
abu = User.create(username: 'abu', email: 'abu@test.com', password: 'abu')
rajah = User.create(username: 'rajah', email: 'rajah@test.com', password: 'rajah')

Book.create(title: 'Becoming', author: 'Michelle Obama', genre: 'Biography', description: 'In her memoir, a work of deep reflection and mesmerizing storytelling, Michelle Obama invites readers into her world, chronicling the experiences that have shaped her—from her childhood on the South Side of Chicago to her years as an executive balancing the demands of motherhood and work, to her time spent at the world’s most famous address. With unerring honesty and lively wit, she describes her triumphs and her disappointments, both public and private, telling her full story as she has lived it—in her own words and on her own terms. Warm, wise, and revelatory, Becoming is the deeply personal reckoning of a woman of soul and substance who has steadily defied expectations—and whose story inspires us to do the same.')
Book.create(title: 'Educated', author: 'Tara Westover', genre: 'Biography', description: 'EDUCATED is an account of the struggle for self-invention. It is a tale of fierce family loyalty, and of the grief that comes with the severing of the closest of ties. With the acute insight that distinguishes all great writers, Westover has, from her singular experience, crafted a universal coming-of-age story, one that gets to the heart of what an education is and what it offers – the perspective to see one’s life through new eyes, and the will to change it.')
Book.create(title: 'Where the Crawdads Sing', author: 'Delia Owens', genre: 'Mystery', description: 'A novel about a young woman determined to make her way in the wilds of North Carolina, and the two men that will break her isolation open.')
Book.create(title: 'All This I Will Give to You', author: 'Dolores Redondo', genre: 'Mystery', description: 'The award-winning, international bestselling page-burner about the secrets and lies of one man that lead another into a treacherous house of strangers…')
Book.create(title: 'The Hate U Give', author: 'Angie Thomas', genre: 'Fiction', description: 'Sixteen-year-old Starr Carter moves between two worlds: the poor neighborhood where she lives and the fancy suburban prep school she attends. The uneasy balance between these worlds is shattered when Starr witnesses the fatal shooting of her childhood best friend Khalil at the hands of a police officer. Khalil was unarmed.

Soon afterward, his death is a national headline. Some are calling him a thug, maybe even a drug dealer and a gangbanger. Protesters are taking to the streets in Khalil’s name. Some cops and the local drug lord try to intimidate Starr and her family. What everyone wants to know is: what really went down that night? And the only person alive who can answer that is Starr.

But what Starr does—or does not—say could upend her community. It could also endanger her life.')
Book.create(title: 'The Power', author: 'Naomi Alderman', genre: 'Fiction', description: 'In The Power the world is a recognisable place: there is a rich Nigerian kid who lounges around the family pool; a foster girl whose religious parents hide their true nature; a local American politician; a tough London girl from a tricky family. But something vital has changed, causing their lives to converge with devastating effect. Teenage girls now have immense physical power - they can cause agonising pain and even death. And, with this small twist of nature, the world changes utterly.')

